### PR TITLE
Updated PH to use AS923-3

### PR DESCRIPTION
**Pull request by carlrakwireless**
Correcting the frequency used on the Philippines from EU868 to AS923-3.

### CODE REVIEW

**Review by gradoj — COMMENTED** [review]
Thanks for the change. I'll get that pulled in as soon as i can. Both AS923-3 and EU868 channels plans can be used in PH so just want to be sure.

**Comment by carlrakwireless** [comment]
Thank you @gradoj . I hope you can review and merge the change asap. Our local community here in PH is very sad. All of us are affected 😢 

Btw, regarding frequency, EU868 and US915 are all occupied here in PH. The frequencies those LoRaWAN regional bands for uplink and downlinks are licensed to someone else and not free. Only the frequencies of AS923-3 are open (915 to 918Mhz). I am doing LoRaWAN since 2018 with TheThingsNetwork as the popular network server so I am very familiar with these things. 

I am not sure if this can help but I created an entire youtube video discussing about frequency to be used here in PH https://youtu.be/tI4lGKxLP1o?t=589

**Comment by retsel86** [comment]
Any Update on this?

**Review by gradoj — APPROVED** [review]

**Comment by carlrakwireless** [comment]
Thank you for merging @gradoj . I just like to ask if you were able to discuss it to other Helium team members. I did this change but I am not 100% sure if this will be the fix or will be needed some FW update on the miners itself.

**Pull request merged**
